# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-12 19:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default=b'toto')),
                ('score', models.IntegerField(default=10)),
                ('cpu', models.IntegerField(default=10)),
                ('time', models.FloatField(default=10)),
                ('process_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('rank', models.IntegerField(default=1)),
                ('source_code', models.TextField(default=b'toto')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
