# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-30 23:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='id',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='button',
            field=models.TextField(default=b'btn-primary'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='cpu',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='process_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='ranking',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='run_id',
            field=models.CharField(default=2, editable=False, max_length=36, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithm',
            name='source_code',
            field=models.TextField(default=b'toto'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='time',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.TextField(default=b'toto'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='rating',
            field=models.IntegerField(default=10),
        ),
    ]
