# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-12 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='score',
            field=models.FloatField(default=10),
        ),
    ]
