# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-08 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='job_link',
            field=models.TextField(default=b'/leaderboard'),
        ),
    ]
