# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-08 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_feed_job_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='job_link',
            field=models.TextField(default=False),
        ),
    ]
